const age = 14;
console.log(age);
const name = "Тимур";
console.log(name);
const  isStudent = true;
console.log(isStudent);
const myString = "";
console.log(myString);
const myNumber = 20;
console.log(myNumber);
const myNull = null;
console.log(myNull);
const userName = prompt("Введіть своє ім’я");
alert("Ви ввели ім'я: " + userName);
console.log(typeof userName);
const userAnswer = confirm("Ви дійсно хочете покинути сторінку?");
console.log(userAnswer);
alert("Увага! Дія може бути небезпечною.");
const isConfirmed = confirm("Ви впевнені що хочете продовжити?");
console.log("Користувач підтвердив дію:", isConfirmed);
